### ISSUE TITLE
[Antora+Kroki] Mermaid sequence diagramm no height/width

### ISSUE THREAD

**Issue by mgh87** [Mogztter/asciidoctor-kroki#134]
Hello, I wanted to use Antora with Kroki for a Mermaid sequence diagram.
It looks like that kroki, returns no sizes for this diagram type.
I tried out other diagrams with kroki which worked.
I tried out the `kroki-fetch-diagram: true`, which also did not work.
This might be related to https://github.com/yuzutech/kroki/issues/151.

Example code of **not** working sequence diagram:
```
[mermaid,fetch-users]
....
sequenceDiagram;
    U->>K: A;
    activate K;
    K->>U: B;
    deactivate K;
    opt empty C;
        U->>P: D!;
        activate P;
        P->>U: E!;
        deactivate P;
    end;
    U->>PP: F;
    PP->>U: G;
....
```

Example code of working sequence diagram:
```
[mermaid,fetch-users]
....
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
....
```

Screenshot from the fetched image that has 0x0 size.
![image](https://user-images.githubusercontent.com/2005565/90268067-b6951a00-de56-11ea-90c8-cf0b0b9c478b.png)

**Comment by Mogztter** [comment]
Hello @mgh87 

> This might be related to https://github.com/yuzutech/kroki/issues/151.

That's correct but the upstream issue is: https://github.com/mermaid-js/mermaid/issues/1490
In theory, we could fix it in Kroki (i.e. extract the width and height from the `viewbox` attribute) but it would be better to fix it directly in Mermaid.
If you have time to fix it in Mermaid that would be great! :+1: 

Since we won't fix this issue in Asciidoctor Kroki, I suggest that we close this issue and continue the discussion at https://github.com/mermaid-js/mermaid/issues/1490 or https://github.com/yuzutech/kroki/issues/151

**Comment by mgh87** [comment]
Ty for the response. Sorry forgot about this issue. I haven't found the issue in mermaid-js and you're completely right it should be fixed there. Closing it.
